#!/bin/sh
# mv review_model_sentence_testing_outputs/yelp/review.0_test_50k_sents review_model_sentence_testing_outputs/yelp/neg_sents_test
# mv review_model_sentence_testing_outputs/yelp/review.1_test_50k_sents review_model_sentence_testing_outputs/yelp/pos_sents_test
# mv review_model_sentence_testing_outputs/imdb/neg_test_reviews_10000sents review_model_sentence_testing_outputs/imdb/neg_sents_test
# mv review_model_sentence_testing_outputs/imdb/pos_test_reviews_10000sents review_model_sentence_testing_outputs/imdb/pos_sents_test

mv review_model_review_testing_outputs/yelp/review.0_test review_model_review_testing_outputs/yelp/neg_reviews_test
mv review_model_review_testing_outputs/yelp/review.1_test review_model_review_testing_outputs/yelp/pos_reviews_test
mv review_model_review_testing_outputs/imdb/neg_test_reviews review_model_review_testing_outputs/imdb/neg_reviews_test
mv review_model_review_testing_outputs/imdb/pos_test_reviews review_model_review_testing_outputs/imdb/pos_reviews_test