#!/bin/sh
# nohup python code/testing_style_transfer.py --label="negative" --truncation="head-and-tail" --model_path=/data/madhu/models/bert-finetuning/saves/yelp_drg/model_2epochs --input_file=/data/chenhao/Sentiment-and-Style-Transfer/data/yelp/sentiment.test.1 --output_file=/data/chenhao/Sentiment-and-Style-Transfer/data/yelp/processed_files_with_bert_with_best_head/sentiment_test_1.txt_flipped_out &> yelp_drg_testing_pos_to_neg_bgst.out &
# nohup python code/testing_style_transfer.py --label="positive" --truncation="head-and-tail" --model_path=/data/madhu/models/bert-finetuning/saves/yelp_drg/model_2epochs --input_file=/data/chenhao/Sentiment-and-Style-Transfer/data/yelp/sentiment.test.0 --output_file=/data/chenhao/Sentiment-and-Style-Transfer/data/yelp/processed_files_with_bert_with_best_head/sentiment_test_0.txt_flipped_out &> yelp_drg_testing_neg_to_pos_bgst.out &

# nohup python code/testing_style_transfer.py --label="negative" --truncation="head-and-tail" --model_path=/data/madhu/models/bert-finetuning/saves/yelp_drg/model_2epochs --input_file=/data/chenhao/Sentiment-and-Style-Transfer/data/yelp/sentiment.test.1 --output_file=/data/chenhao/Sentiment-and-Style-Transfer/data/yelp/processed_files_with_bert_with_best_head/delete_retrieve_edit_model/tfidf/reference_1.txt_out &> yelp_drg_testing_pos_to_neg_ggst.out &
# nohup python code/testing_style_transfer.py --label="positive" --truncation="head-and-tail" --model_path=/data/madhu/models/bert-finetuning/saves/yelp_drg/model_2epochs --input_file=/data/chenhao/Sentiment-and-Style-Transfer/data/yelp/sentiment.test.0 --output_file=/data/chenhao/Sentiment-and-Style-Transfer/data/yelp/processed_files_with_bert_with_best_head/delete_retrieve_edit_model/tfidf/reference_0.txt_out &> yelp_drg_testing_neg_to_pos_ggst.out &

nohup python code/testing_style_transfer.py --truncation="head-and-tail" --model_path=/data/madhu/models/bert-finetuning/saves/yelp_drg/model_2epochs --pos_input_file=/data/chenhao/Sentiment-and-Style-Transfer/data/yelp/sentiment.test.1 --neg_input_file=/data/chenhao/Sentiment-and-Style-Transfer/data/yelp/sentiment.test.0 --pos_output_file=/data/chenhao/Sentiment-and-Style-Transfer/data/yelp/processed_files_with_bert_with_best_head/sentiment_test_1.txt_flipped_out --neg_output_file=/data/chenhao/Sentiment-and-Style-Transfer/data/yelp/processed_files_with_bert_with_best_head/sentiment_test_0.txt_flipped_out &> yelp_drg_testing_bgst.out &


nohup python code/testing_style_transfer.py --truncation="head-and-tail" --model_path=/data/madhu/models/bert-finetuning/saves/yelp_drg/model_2epochs --pos_input_file=/data/chenhao/Sentiment-and-Style-Transfer/data/yelp/sentiment.test.1 --pos_output_file=/data/chenhao/Sentiment-and-Style-Transfer/data/yelp/processed_files_with_bert_with_best_head/delete_retrieve_edit_model/tfidf/reference_1.txt_out --neg_input_file=/data/chenhao/Sentiment-and-Style-Transfer/data/yelp/sentiment.test.0 --neg_output_file=/data/chenhao/Sentiment-and-Style-Transfer/data/yelp/processed_files_with_bert_with_best_head/delete_retrieve_edit_model/tfidf/reference_0.txt_out &> yelp_drg_testing_ggst.out &


nohup python code/testing.py --label="positive" --truncation="head-and-tail" --model_path=/data/madhu/models/bert-finetuning/saves/yelp_drg/model_2epochs --input_file=/data/chenhao/Sentiment-and-Style-Transfer/data/yelp/sentiment.test.1 &> yelp_drg_testing_pos.out &
nohup python code/testing.py --label="negative" --truncation="head-and-tail" --model_path=/data/madhu/models/bert-finetuning/saves/yelp_drg/model_2epochs --input_file=/data/chenhao/Sentiment-and-Style-Transfer/data/yelp/sentiment.test.0 &> yelp_drg_testing_neg.out &


# Amazon datasets
# nohup python code/testing_style_transfer.py --label="negative" --truncation="head-and-tail" --model_path=/data/madhu/models/bert-finetuning/saves/amazon_drg/model_1epochs --input_file=/data/chenhao/Sentiment-and-Style-Transfer/data/amazon/sentiment.test.1 --output_file=/data/chenhao/Sentiment-and-Style-Transfer/data/amazon/processed_files_with_bert_with_best_head/sentiment_test_1.txt_flipped_out &> amazon_drg_testing_pos_to_neg_bgst.out &
# python code/testing_style_transfer.py --label="positive" --truncation="head-and-tail" --model_path=/data/madhu/models/bert-finetuning/saves/amazon_drg/model_1epochs --input_file=/data/chenhao/Sentiment-and-Style-Transfer/data/amazon/sentiment.test.0 --output_file=/data/chenhao/Sentiment-and-Style-Transfer/data/amazon/processed_files_with_bert_with_best_head/sentiment_test_0.txt_flipped_out &> amazon_drg_testing_neg_to_pos_bgst.out &

# nohup python code/testing_style_transfer.py --label="negative" --truncation="head-and-tail" --model_path=/data/madhu/models/bert-finetuning/saves/amazon_drg/model_1epochs --input_file=/data/chenhao/Sentiment-and-Style-Transfer/data/amazon/sentiment.test.1 --output_file=/data/chenhao/Sentiment-and-Style-Transfer/data/amazon/processed_files_with_bert_with_best_head/delete_retrieve_edit_model/tfidf/reference_1.txt_out &> amazon_drg_testing_pos_to_neg_ggst.out &
# nohup python code/testing_style_transfer.py --label="positive" --truncation="head-and-tail" --model_path=/data/madhu/models/bert-finetuning/saves/amazon_drg/model_1epochs --input_file=/data/chenhao/Sentiment-and-Style-Transfer/data/amazon/sentiment.test.0 --output_file=/data/chenhao/Sentiment-and-Style-Transfer/data/amazon/processed_files_with_bert_with_best_head/delete_retrieve_edit_model/tfidf/reference_0.txt_out &> amazon_drg_testing_neg_to_pos_ggst.out &

nohup python code/testing_style_transfer.py --truncation="head-and-tail" --model_path=/data/madhu/models/bert-finetuning/saves/amazon_drg/model_1epochs --pos_input_file=/data/chenhao/Sentiment-and-Style-Transfer/data/amazon/sentiment.test.1 --pos_output_file=/data/chenhao/Sentiment-and-Style-Transfer/data/amazon/processed_files_with_bert_with_best_head/sentiment_test_1.txt_flipped_out --neg_input_file=/data/chenhao/Sentiment-and-Style-Transfer/data/amazon/sentiment.test.0 --neg_output_file=/data/chenhao/Sentiment-and-Style-Transfer/data/amazon/processed_files_with_bert_with_best_head/sentiment_test_0.txt_flipped_out &> amazon_drg_testing_bgst.out &

nohup python code/testing_style_transfer.py --truncation="head-and-tail" --model_path=/data/madhu/models/bert-finetuning/saves/amazon_drg/model_1epochs --pos_input_file=/data/chenhao/Sentiment-and-Style-Transfer/data/amazon/sentiment.test.1 --pos_output_file=/data/chenhao/Sentiment-and-Style-Transfer/data/amazon/processed_files_with_bert_with_best_head/delete_retrieve_edit_model/tfidf/reference_1.txt_out --neg_input_file=/data/chenhao/Sentiment-and-Style-Transfer/data/amazon/sentiment.test.0 --neg_output_file=/data/chenhao/Sentiment-and-Style-Transfer/data/amazon/processed_files_with_bert_with_best_head/delete_retrieve_edit_model/tfidf/reference_0.txt_out &> amazon_drg_testing_ggst.out &


nohup python code/testing.py --label="positive" --truncation="head-and-tail" --model_path=/data/madhu/models/bert-finetuning/saves/amazon_drg/model_1epochs --input_file=/data/chenhao/Sentiment-and-Style-Transfer/data/amazon/sentiment.test.1 &> amazon_drg_testing_pos.out &
nohup python code/testing.py --label="negative" --truncation="head-and-tail" --model_path=/data/madhu/models/bert-finetuning/saves/amazon_drg/model_1epochs --input_file=/data/chenhao/Sentiment-and-Style-Transfer/data/amazon/sentiment.test.0 &> amazon_drg_testing_neg.out &